Reverted a change from 18-Mar-2023 which removed mceNonEditable from break
scribe777/wfce-ote pull request #133
Opened 2024-07-05 13:48 UTC by scribe777

@catsmith, mceNonEditable was removed from break elements with this commit:

https://github.com/scribe777/wfce-ote/commit/20186b2c050cb3b0de067c3d7fa9df8e0cee2aa6

This allows a user to place their cursor in the middle of a break, e.g., ‹PB 1r› and hit [enter] which will add the linebreak within the span of the PB display.

I am sure you had a reason for removing the mceNonEditable flag from break, but this is causing problems for our editors now so I have reverted it here.  I will leave this PR open and unmerged until we discuss, in case you have a better solution.

2024-07-05 14:04 UTC, catsmith commented
was originally #110. I think this was to allow page break numbers to be properly edited and updated in the interface. I need to look into the use case and why I had to change the classes - I was moving towards the MUYA version because it had behaviour I thought we wanted. I'll need to roll it back and test locally. Probably won't be soon though. No-one our end has had any issues with this its been live for ages.

2024-07-05 14:06 UTC, catsmith commented
Hang on, you transcribe by page why is anyone even touching a page break ;-)

2024-07-05 14:22 UTC, tgriffitts-ns commented
Yes, true, but we still have the PB at the start of content and this is not only for pb but for lb and cb.

2024-07-05 14:27 UTC, catsmith commented
Hmm I think I remember why I did it and I think that is a reason we care about but I will need to check. There might be another way around it.

2024-07-05 15:06 UTC, scribe777 commented
Well, @catsmith, your tests are failing.  Maybe this tells us why you did it?

2024-07-05 15:11 UTC, catsmith commented
No that tells us that the mceNonEditable class appears everywhere in the tests! I think that it was because if it is non editable the visible page number is never changed even if you edit it in the B menu which is just confusing and wrong. I think the reason it wasn't updating was that class which Martin had taken out in the MUYA version so that the page numbers could be changed.

2024-07-06 17:31 UTC, catsmith commented
Original issue for reference https://github.com/scribe777/wfce-ote/issues/109

2024-07-06 19:08 UTC, catsmith requested changes
Please check out the alternative solution in #135 to see if that also meets the requirements. It will allow us to keep the new functionality but without the problem you found.

2024-07-30 12:18 UTC, closed without merging

2024-07-30 12:19 UTC, scribe777 commented
fixed with Cat's alternate PR.